### ISSUE TITLE
Where is the changelog?

### ISSUE THREAD

**Issue by lightswitch05** [ipdata/python#24]
I'm doing some maintenance work to upgrade dependencies. Right now I'm at version `3.4.3`. I see the latest version is `4.0.7`. When doing updates, I like to go through a changelog to see if there is any breaking changes I should keep a lookout for. I seem to be unable to find the changelog for this library. I assume going from 3 to 4 is potentially a big upgrade. Can you point me to where the changelog is to help with this update?

**Comment by jonathan-kosgei** [comment]
Hi @lightswitch05 this is great idea and am sorry we did not already include one, we will do so going forward.
