### ISSUE TITLE
Add support for accessing fields in nested objects

### ISSUE THREAD

**Issue by jonathan-kosgei** [ipdata/python#7]
Currently the below fails. We should fix the main library to support all the fields in the API response's nested  objects.

```
from ipdata import ipdata
from pprint import pprint
# Create an instance of an ipdata object. Replace `test` with your API Key
ipdata = ipdata.IPData('test')
response = ipdata.lookup('8.8.8.8',fields=['time_zone.name'])
pprint(response)
```

**Comment by stasdavydov** [comment]
Is it okay if I will filter result fields only without validation? Or I should fix `validate_fields()` with all the subsequent fields also?

**Comment by jonathan-kosgei** [comment]
This would actually need to be implemented in the API since the values in fields are passed directly to the API.
